
services:
  mysql:
    image: mysql:8
    container_name: setu-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: setu
      MYSQL_USER: setu
      MYSQL_PASSWORD: setu
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: setu-backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/setu
      SPRING_DATASOURCE_USERNAME: setu
      SPRING_DATASOURCE_PASSWORD: setu
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./setu-frontend
      dockerfile: Dockerfile
    container_name: setu-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data: